<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <ProjectReference Include="..\Servicio_Clientes\Servicio_Clientes.csproj" />
    <ProjectReference Include="..\Servicio_Ventas\Servicio_Ventas.csproj" />
  </ItemGroup>

</Project>
